import type { Customer } from "@/types/customer";

export const mockCustomers: Customer[] = [
  {
    id: "cust-001",
    firstName: "Maaike",
    lastName: "de Vries",
    companyName: "De Vries Advies",
    email: "maaike@example.com",
    phone: "+31 6 1234 5678",
    destination: "Noorwegen",
    travelPeriod: "12 augustus - 24 augustus 2026",
    status: "Reisvoorstel",
    notes: "Wil graag fjorden combineren met rustige accommodaties en korte wandelingen.",
    offerNumber: "2026-2612",
    quoteSent: true,
    quoteSentDate: "2026-06-01",
    quoteFollowUpDate: "2026-06-04",
    quoteConfirmed: true,
    quoteConfirmedDate: "2026-06-06",
    invoiceDate: "2026-06-07",
    invoiceNumber: "2026-2612",
    tripNumber: "2026-2612",
    tripName: "Winterreis Noorwegen op maat",
    departureDate: "2026-12-12",
    returnDate: "2026-12-21",
    totalAmount: "4850",
    paymentType: "deposit_and_final",
    depositDueDate: "2026-06-15",
    depositReceived: false,
    depositDate: "",
    finalPaymentDueDate: "2026-10-31",
    finalPaymentReceived: false,
    finalPaymentDate: "",
    fullPaymentDueDate: "",
    fullPaymentReceived: false,
    fullPaymentDate: "",
    travelDocumentsPrepareFromDate: "2026-11-28",
    travelDocumentsPlannedSendDate: "2026-12-05",
    travelDocumentsPrepared: false,
    travelDocumentsSent: false,
    travelDocumentsSentDate: "",
    postTripContacted: false,
    postTripContactDate: "",
    googleReviewLinkSent: false,
    googleReviewLinkSentDate: "",
    travelers: [
      {
        id: "trav-001",
        firstName: "Maaike",
        lastName: "de Vries",
        birthDate: "1982-04-12",
        type: "adult",
        notes: "Hoofdboeker"
      },
      {
        id: "trav-002",
        firstName: "Karin",
        lastName: "de Vries",
        birthDate: "1984-09-03",
        type: "adult",
        notes: ""
      }
    ]
  },
  {
    id: "cust-002",
    firstName: "Thomas",
    lastName: "Bakker",
    companyName: "Bakker Studio",
    email: "thomas@example.com",
    phone: "+31 6 2345 6789",
    destination: "IJsland",
    travelPeriod: "3 oktober - 11 oktober 2026",
    status: "Intake gepland",
    notes: "Interesse in fotografie, warmwaterbronnen en een compacte rondreis met huurauto.",
    offerNumber: "2026-2613",
    quoteSent: false,
    quoteSentDate: "",
    quoteFollowUpDate: "2026-06-05",
    quoteConfirmed: false,
    quoteConfirmedDate: "",
    invoiceDate: "",
    invoiceNumber: "",
    tripNumber: "2026-2408",
    tripName: "Fotoreis IJsland",
    departureDate: "2026-10-03",
    returnDate: "2026-10-11",
    totalAmount: "3920",
    paymentType: "deposit_and_final",
    depositDueDate: "",
    depositReceived: true,
    depositDate: "2026-05-29",
    finalPaymentDueDate: "",
    finalPaymentReceived: false,
    finalPaymentDate: "",
    fullPaymentDueDate: "",
    fullPaymentReceived: false,
    fullPaymentDate: "",
    travelDocumentsPrepareFromDate: "2026-09-19",
    travelDocumentsPlannedSendDate: "2026-09-26",
    travelDocumentsPrepared: false,
    travelDocumentsSent: false,
    travelDocumentsSentDate: "",
    postTripContacted: false,
    postTripContactDate: "",
    googleReviewLinkSent: false,
    googleReviewLinkSentDate: "",
    travelers: [
      {
        id: "trav-003",
        firstName: "Thomas",
        lastName: "Bakker",
        birthDate: "1979-11-18",
        type: "adult",
        notes: "Fotografie"
      }
    ]
  },
  {
    id: "cust-003",
    firstName: "Sanne",
    lastName: "Meijer",
    companyName: "Particulier",
    email: "sanne@example.com",
    phone: "+31 6 3456 7890",
    destination: "Fins Lapland",
    travelPeriod: "20 februari - 27 februari 2027",
    status: "Nieuwe aanvraag",
    notes: "Gezinsreis met focus op noorderlicht, huskytocht en voldoende rustdagen.",
    offerNumber: "",
    quoteSent: false,
    quoteSentDate: "",
    quoteFollowUpDate: "",
    quoteConfirmed: false,
    quoteConfirmedDate: "",
    invoiceDate: "",
    invoiceNumber: "",
    tripNumber: "",
    tripName: "Lapland gezinsreis",
    departureDate: "2027-02-20",
    returnDate: "2027-02-27",
    totalAmount: "",
    paymentType: "deposit_and_final",
    depositDueDate: "",
    depositReceived: false,
    depositDate: "",
    finalPaymentDueDate: "",
    finalPaymentReceived: false,
    finalPaymentDate: "",
    fullPaymentDueDate: "",
    fullPaymentReceived: false,
    fullPaymentDate: "",
    travelDocumentsPrepareFromDate: "2027-02-06",
    travelDocumentsPlannedSendDate: "2027-02-13",
    travelDocumentsPrepared: false,
    travelDocumentsSent: false,
    travelDocumentsSentDate: "",
    postTripContacted: false,
    postTripContactDate: "",
    googleReviewLinkSent: false,
    googleReviewLinkSentDate: "",
    travelers: [
      {
        id: "trav-004",
        firstName: "Sanne",
        lastName: "Meijer",
        birthDate: "1988-02-24",
        type: "adult",
        notes: "Hoofdboeker"
      },
      {
        id: "trav-005",
        firstName: "Lotte",
        lastName: "Meijer",
        birthDate: "2014-07-09",
        type: "child",
        notes: ""
      }
    ]
  }
];
